# Motors
right drive motor: D
left drive motor: B
front drive motor: A
latch motor: C

# GrovePi Sensors
hall effect sensor: 5
ultrasonic sensor: 6
line finders:
  - 2
  - 3
line finder positions:
  - 0
  - 6

# BrickPi Sensors
touch sensor: 4
color line sensors:
  - 1
  - 2
  - 3
color line sensor positions:
  - 2
  - 3
  - 4

# Dimensions, measured in mm
rear wheel diameter: 60
front wheel diameter: 60

# PID
Kp: 0.1
Ki: 0.1
Kd: 0.1
base motor power: 50
max line value: 64