# Motors
right drive motor: D
left drive motor: B
latch motor: C

# GrovePi Sensors
hall effect sensor: 5
ultrasonic sensor: 6
line finders:
  - 2
  - 3
line finder positions:
  - 0
  - 9

# BrickPi Sensors
touch sensor: 4

# Analog Sensors
ir sensors:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
ir positions:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8

# Dimensions, measured in mm
rear wheel diameter: 60
front wheel diameter: 60

# PID
Kp: 0.1
Ki: 0.1
Kd: 0.1
base motor power: 50
threshold: 100