# Motors
right drive motor: D
left drive motor: A
latch motor: B

# GrovePi Sensors
hall effect sensor: 5
line finders:
line finder positions:

# BrickPi Sensors
touch sensor: 4
ultrasonic sensor: 3

# Analog Sensors
ir sensors:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
ir positions:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7

# Dimensions, measured in mm
rear wheel diameter: 60
front wheel diameter: 60
dia pitch latch gear: 4

# PID
#Kp: 20
#Ki: 0
#Kd: 0
#base motor power: 20
Kp: 100
Ki: 0
Kd: 10
base motor speed: 100
speed change: 300
threshold: 70
