# Motors
right drive motor: A
left drive motor: D
latch motor: C

# GrovePi Sensors
hall effect sensor: 5
ultrasonic sensor: 6
line finders:
line finder positions:

# BrickPi Sensors
touch sensor: 4

# Analog Sensors
ir sensors:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
ir positions:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7

# Dimensions, measured in mm
rear wheel diameter: 60
front wheel diameter: 60

# PID
Kp: 10
Ki: 0
Kd: 0
base motor power: 50
threshold: 100
